name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Construir imagem Docker
        run: docker build -t meu-app .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir e enviar imagem para Docker Hub
        run: |
          docker build -t meu-usuario/meu-app .
          docker tag meu-usuario/meu-app meu-usuario/meu-app:latest
          docker push meu-usuario/meu-app:latest

      - name: Deploy no Servidor (exemplo com SSH)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull meu-usuario/meu-app:latest
            docker stop meu-app || true
            docker rm meu-app || true
            docker run -d --name meu-app -p 3000:3000 meu-usuario/meu-app:latest
